# Generated by Django 3.0.8 on 2020-09-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bloks_talk'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='basicpwd',
            field=models.CharField(default='111', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='time',
            field=models.CharField(default='0', max_length=32),
            preserve_default=False,
        ),
    ]
