# Generated by Django 3.0.8 on 2020-09-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200927_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='aut',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
