# Generated by Django 3.0.8 on 2020-09-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_users_aut'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginTime',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('tk_user', models.CharField(max_length=32)),
                ('tk_time', models.CharField(max_length=32)),
            ],
        ),
    ]
